name = "ada_lib_aunit"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""

project-files = "ada_lib_aunit.gpr"

tags = []

[[depends-on]]
aunit = "~0.1.0-dev"

[[pins]]
aunit = { path='../../aunit' }

[[pins]]
alr_environment = { path='../..' }

[[depends-on]]
gnatcoll_minimal = "*"


