# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=make
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

# If no configuration is specified, "Debug" will be used
ifndef CFG
CFG=Debug
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=Gnoga
CFG_INC=
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/gnoga-gui-plugin-ace_editor.o \
	$(OUTDIR)/adablog-controller.o $(OUTDIR)/adablog-main.o \
	$(OUTDIR)/adablog-migrations.o $(OUTDIR)/adablog-view.o \
	$(OUTDIR)/adaedit.o $(OUTDIR)/othello_game.o \
	$(OUTDIR)/othello_pkg-callbacks.o $(OUTDIR)/othello_pkg.o \
	$(OUTDIR)/gnoga-gui-plugin-boot_strap.o $(OUTDIR)/chattanooga-db.o \
	$(OUTDIR)/chattanooga-program.o $(OUTDIR)/chattanooga-ui.o \
	$(OUTDIR)/connect_four.o $(OUTDIR)/connectfour.o \
	$(OUTDIR)/db_maker.o $(OUTDIR)/movies.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui-widget.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui.o $(OUTDIR)/about_dialog_pkg.o \
	$(OUTDIR)/block_engine.o $(OUTDIR)/game_engine.o \
	$(OUTDIR)/gnoga_extras.o $(OUTDIR)/linxtris.o \
	$(OUTDIR)/main_window_pkg-callbacks.o $(OUTDIR)/main_window_pkg.o \
	$(OUTDIR)/new_score_dialog_pkg.o $(OUTDIR)/preferences_window_pkg.o \
	$(OUTDIR)/scores_window_pkg.o \
	$(OUTDIR)/gnoga-gui-plugin-message_boxes.o \
	$(OUTDIR)/field-operations.o $(OUTDIR)/mine_detector.o \
	$(OUTDIR)/user_if.o $(OUTDIR)/password_gen-program.o \
	$(OUTDIR)/password_gen-ui.o $(OUTDIR)/random_int-program.o \
	$(OUTDIR)/random_int-ui.o $(OUTDIR)/snake-connection.o \
	$(OUTDIR)/snake-main.o $(OUTDIR)/tic_tac_toe-program.o \
	$(OUTDIR)/tic_tac_toe-ui-logic.o $(OUTDIR)/tic_tac_toe-ui.o \
	$(OUTDIR)/tutorial_01.o $(OUTDIR)/tutorial_02.o \
	$(OUTDIR)/tutorial_03.o $(OUTDIR)/tutorial_04.o \
	$(OUTDIR)/tutorial_05.o $(OUTDIR)/tutorial_06.o \
	$(OUTDIR)/tutorial_07.o $(OUTDIR)/tutorial_08.o \
	$(OUTDIR)/tutorial_09.o $(OUTDIR)/tutorial_widget.o \
	$(OUTDIR)/tutorial_10.o $(OUTDIR)/tutorial_11.o \
	$(OUTDIR)/tutorial_01.o $(OUTDIR)/gnoga-application-gtk_window.o \
	$(OUTDIR)/gnoga-application-multi_connect.o \
	$(OUTDIR)/gnoga-application-singleton.o \
	$(OUTDIR)/gnoga-application.o $(OUTDIR)/gnoga-client-bind_page.o \
	$(OUTDIR)/gnoga-client-storage.o $(OUTDIR)/gnoga-gui-base.o \
	$(OUTDIR)/gnoga-gui-document.o \
	$(OUTDIR)/gnoga-gui-element-canvas-context_2d-plotting.o \
	$(OUTDIR)/gnoga-gui-element-canvas-context_2d.o \
	$(OUTDIR)/gnoga-gui-element-canvas.o \
	$(OUTDIR)/gnoga-gui-element-common.o \
	$(OUTDIR)/gnoga-gui-element-form-fieldset.o \
	$(OUTDIR)/gnoga-gui-element-form.o \
	$(OUTDIR)/gnoga-gui-element-iframe.o \
	$(OUTDIR)/gnoga-gui-element-list.o \
	$(OUTDIR)/gnoga-gui-element-multimedia.o \
	$(OUTDIR)/gnoga-gui-element-phrase.o \
	$(OUTDIR)/gnoga-gui-element-section.o \
	$(OUTDIR)/gnoga-gui-element-style_block.o \
	$(OUTDIR)/gnoga-gui-element-svg.o \
	$(OUTDIR)/gnoga-gui-element-table.o $(OUTDIR)/gnoga-gui-element.o \
	$(OUTDIR)/gnoga-gui-location.o $(OUTDIR)/gnoga-gui-navigator.o \
	$(OUTDIR)/gnoga-gui-plugin-ace_editor.o \
	$(OUTDIR)/gnoga-gui-plugin-boot_strap.o \
	$(OUTDIR)/gnoga-gui-plugin-jquery.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui-widget.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui.o \
	$(OUTDIR)/gnoga-gui-plugin-macgap.o \
	$(OUTDIR)/gnoga-gui-plugin-message_boxes.o \
	$(OUTDIR)/gnoga-gui-screen.o $(OUTDIR)/gnoga-gui-view-card.o \
	$(OUTDIR)/gnoga-gui-view-console.o $(OUTDIR)/gnoga-gui-view-docker.o \
	$(OUTDIR)/gnoga-gui-view-grid.o $(OUTDIR)/gnoga-gui-view.o \
	$(OUTDIR)/gnoga-gui-window.o $(OUTDIR)/gnoga-server-connection.o \
	$(OUTDIR)/gnoga-server-database-mysql.o \
	$(OUTDIR)/gnoga-server-database-sqlite.o \
	$(OUTDIR)/gnoga-server-database.o $(OUTDIR)/gnoga-server-migration.o \
	$(OUTDIR)/gnoga-server-mime.o $(OUTDIR)/gnoga-server-model-queries.o \
	$(OUTDIR)/gnoga-server-model-table.o $(OUTDIR)/gnoga-server-model.o \
	$(OUTDIR)/gnoga-server-template_parser-python.o \
	$(OUTDIR)/gnoga-server-template_parser-simple.o \
	$(OUTDIR)/gnoga-server-template_parser.o $(OUTDIR)/gnoga-server.o \
	$(OUTDIR)/gnoga-types-colors.o $(OUTDIR)/gnoga-types.o \
	$(OUTDIR)/gnoga.o $(OUTDIR)/gnoga_doc-main.o \
	$(OUTDIR)/gnoga_doc-token.o $(OUTDIR)/gnoga_doc.o \
	$(OUTDIR)/gnoga_make-main.o $(OUTDIR)/gnoga_make.o
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/gnoga-gui-plugin-ace_editor.o \
	$(OUTDIR)/adablog-controller.o $(OUTDIR)/adablog-main.o \
	$(OUTDIR)/adablog-migrations.o $(OUTDIR)/adablog-view.o \
	$(OUTDIR)/adaedit.o $(OUTDIR)/othello_game.o \
	$(OUTDIR)/othello_pkg-callbacks.o $(OUTDIR)/othello_pkg.o \
	$(OUTDIR)/gnoga-gui-plugin-boot_strap.o $(OUTDIR)/chattanooga-db.o \
	$(OUTDIR)/chattanooga-program.o $(OUTDIR)/chattanooga-ui.o \
	$(OUTDIR)/connect_four.o $(OUTDIR)/connectfour.o \
	$(OUTDIR)/db_maker.o $(OUTDIR)/movies.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui-widget.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui.o $(OUTDIR)/about_dialog_pkg.o \
	$(OUTDIR)/block_engine.o $(OUTDIR)/game_engine.o \
	$(OUTDIR)/gnoga_extras.o $(OUTDIR)/linxtris.o \
	$(OUTDIR)/main_window_pkg-callbacks.o $(OUTDIR)/main_window_pkg.o \
	$(OUTDIR)/new_score_dialog_pkg.o $(OUTDIR)/preferences_window_pkg.o \
	$(OUTDIR)/scores_window_pkg.o \
	$(OUTDIR)/gnoga-gui-plugin-message_boxes.o \
	$(OUTDIR)/field-operations.o $(OUTDIR)/mine_detector.o \
	$(OUTDIR)/user_if.o $(OUTDIR)/password_gen-program.o \
	$(OUTDIR)/password_gen-ui.o $(OUTDIR)/random_int-program.o \
	$(OUTDIR)/random_int-ui.o $(OUTDIR)/snake-connection.o \
	$(OUTDIR)/snake-main.o $(OUTDIR)/tic_tac_toe-program.o \
	$(OUTDIR)/tic_tac_toe-ui-logic.o $(OUTDIR)/tic_tac_toe-ui.o \
	$(OUTDIR)/tutorial_01.o $(OUTDIR)/tutorial_02.o \
	$(OUTDIR)/tutorial_03.o $(OUTDIR)/tutorial_04.o \
	$(OUTDIR)/tutorial_05.o $(OUTDIR)/tutorial_06.o \
	$(OUTDIR)/tutorial_07.o $(OUTDIR)/tutorial_08.o \
	$(OUTDIR)/tutorial_09.o $(OUTDIR)/tutorial_widget.o \
	$(OUTDIR)/tutorial_10.o $(OUTDIR)/tutorial_11.o \
	$(OUTDIR)/tutorial_01.o $(OUTDIR)/gnoga-application-gtk_window.o \
	$(OUTDIR)/gnoga-application-multi_connect.o \
	$(OUTDIR)/gnoga-application-singleton.o \
	$(OUTDIR)/gnoga-application.o $(OUTDIR)/gnoga-client-bind_page.o \
	$(OUTDIR)/gnoga-client-storage.o $(OUTDIR)/gnoga-gui-base.o \
	$(OUTDIR)/gnoga-gui-document.o \
	$(OUTDIR)/gnoga-gui-element-canvas-context_2d-plotting.o \
	$(OUTDIR)/gnoga-gui-element-canvas-context_2d.o \
	$(OUTDIR)/gnoga-gui-element-canvas.o \
	$(OUTDIR)/gnoga-gui-element-common.o \
	$(OUTDIR)/gnoga-gui-element-form-fieldset.o \
	$(OUTDIR)/gnoga-gui-element-form.o \
	$(OUTDIR)/gnoga-gui-element-iframe.o \
	$(OUTDIR)/gnoga-gui-element-list.o \
	$(OUTDIR)/gnoga-gui-element-multimedia.o \
	$(OUTDIR)/gnoga-gui-element-phrase.o \
	$(OUTDIR)/gnoga-gui-element-section.o \
	$(OUTDIR)/gnoga-gui-element-style_block.o \
	$(OUTDIR)/gnoga-gui-element-svg.o \
	$(OUTDIR)/gnoga-gui-element-table.o $(OUTDIR)/gnoga-gui-element.o \
	$(OUTDIR)/gnoga-gui-location.o $(OUTDIR)/gnoga-gui-navigator.o \
	$(OUTDIR)/gnoga-gui-plugin-ace_editor.o \
	$(OUTDIR)/gnoga-gui-plugin-boot_strap.o \
	$(OUTDIR)/gnoga-gui-plugin-jquery.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui-widget.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui.o \
	$(OUTDIR)/gnoga-gui-plugin-macgap.o \
	$(OUTDIR)/gnoga-gui-plugin-message_boxes.o \
	$(OUTDIR)/gnoga-gui-screen.o $(OUTDIR)/gnoga-gui-view-card.o \
	$(OUTDIR)/gnoga-gui-view-console.o $(OUTDIR)/gnoga-gui-view-docker.o \
	$(OUTDIR)/gnoga-gui-view-grid.o $(OUTDIR)/gnoga-gui-view.o \
	$(OUTDIR)/gnoga-gui-window.o $(OUTDIR)/gnoga-server-connection.o \
	$(OUTDIR)/gnoga-server-database-mysql.o \
	$(OUTDIR)/gnoga-server-database-sqlite.o \
	$(OUTDIR)/gnoga-server-database.o $(OUTDIR)/gnoga-server-migration.o \
	$(OUTDIR)/gnoga-server-mime.o $(OUTDIR)/gnoga-server-model-queries.o \
	$(OUTDIR)/gnoga-server-model-table.o $(OUTDIR)/gnoga-server-model.o \
	$(OUTDIR)/gnoga-server-template_parser-python.o \
	$(OUTDIR)/gnoga-server-template_parser-simple.o \
	$(OUTDIR)/gnoga-server-template_parser.o $(OUTDIR)/gnoga-server.o \
	$(OUTDIR)/gnoga-types-colors.o $(OUTDIR)/gnoga-types.o \
	$(OUTDIR)/gnoga.o $(OUTDIR)/gnoga_doc-main.o \
	$(OUTDIR)/gnoga_doc-token.o $(OUTDIR)/gnoga_doc.o \
	$(OUTDIR)/gnoga_make-main.o $(OUTDIR)/gnoga_make.o

COMPILE=gnat -c -g $(CFG_INC) -o "$(OUTDIR)/$(*F).o" "$<"
LINK=gnat -g -o "$(OUTFILE)" $(OBJ) $(CFG_LIB)
COMPILE_ADA=gnat -c -g -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_ADB=gnat -c -g -o "$(OUTDIR)/$(*F).o" "$<"

# Pattern rules
$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/ace_editor/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/chattanooga/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adablog/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adaedit/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/mine_detector/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-08/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-01/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/linxtris/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/snake/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial_01/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/jqueryui/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/message_boxes/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-09/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/bootstrap/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-04/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/db_maker/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/password_gen/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-06/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-05/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tools/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-11/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-07/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adaothello/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-10/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/connect_four/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-02/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/tic_tac_toe/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-03/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/random_int/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/ace_editor/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/chattanooga/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adablog/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adaedit/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/mine_detector/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-08/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-01/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/linxtris/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/snake/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial_01/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/jqueryui/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/message_boxes/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-09/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/bootstrap/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-04/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/db_maker/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/password_gen/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-06/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-05/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tools/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-11/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-07/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adaothello/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-10/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/connect_four/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-02/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/tic_tac_toe/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-03/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/random_int/%.adb
	$(COMPILE_ADB)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR) $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall
	@$(MAKE) -f "$(strip $(MAKEFILE_LIST))" $(MAKEFLAGS) all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=Gnoga
CFG_INC=
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/gnoga-gui-plugin-ace_editor.o \
	$(OUTDIR)/adablog-controller.o $(OUTDIR)/adablog-main.o \
	$(OUTDIR)/adablog-migrations.o $(OUTDIR)/adablog-view.o \
	$(OUTDIR)/adaedit.o $(OUTDIR)/othello_game.o \
	$(OUTDIR)/othello_pkg-callbacks.o $(OUTDIR)/othello_pkg.o \
	$(OUTDIR)/gnoga-gui-plugin-boot_strap.o $(OUTDIR)/chattanooga-db.o \
	$(OUTDIR)/chattanooga-program.o $(OUTDIR)/chattanooga-ui.o \
	$(OUTDIR)/connect_four.o $(OUTDIR)/connectfour.o \
	$(OUTDIR)/db_maker.o $(OUTDIR)/movies.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui-widget.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui.o $(OUTDIR)/about_dialog_pkg.o \
	$(OUTDIR)/block_engine.o $(OUTDIR)/game_engine.o \
	$(OUTDIR)/gnoga_extras.o $(OUTDIR)/linxtris.o \
	$(OUTDIR)/main_window_pkg-callbacks.o $(OUTDIR)/main_window_pkg.o \
	$(OUTDIR)/new_score_dialog_pkg.o $(OUTDIR)/preferences_window_pkg.o \
	$(OUTDIR)/scores_window_pkg.o \
	$(OUTDIR)/gnoga-gui-plugin-message_boxes.o \
	$(OUTDIR)/field-operations.o $(OUTDIR)/mine_detector.o \
	$(OUTDIR)/user_if.o $(OUTDIR)/password_gen-program.o \
	$(OUTDIR)/password_gen-ui.o $(OUTDIR)/random_int-program.o \
	$(OUTDIR)/random_int-ui.o $(OUTDIR)/snake-connection.o \
	$(OUTDIR)/snake-main.o $(OUTDIR)/tic_tac_toe-program.o \
	$(OUTDIR)/tic_tac_toe-ui-logic.o $(OUTDIR)/tic_tac_toe-ui.o \
	$(OUTDIR)/tutorial_01.o $(OUTDIR)/tutorial_02.o \
	$(OUTDIR)/tutorial_03.o $(OUTDIR)/tutorial_04.o \
	$(OUTDIR)/tutorial_05.o $(OUTDIR)/tutorial_06.o \
	$(OUTDIR)/tutorial_07.o $(OUTDIR)/tutorial_08.o \
	$(OUTDIR)/tutorial_09.o $(OUTDIR)/tutorial_widget.o \
	$(OUTDIR)/tutorial_10.o $(OUTDIR)/tutorial_11.o \
	$(OUTDIR)/tutorial_01.o $(OUTDIR)/gnoga-application-gtk_window.o \
	$(OUTDIR)/gnoga-application-multi_connect.o \
	$(OUTDIR)/gnoga-application-singleton.o \
	$(OUTDIR)/gnoga-application.o $(OUTDIR)/gnoga-client-bind_page.o \
	$(OUTDIR)/gnoga-client-storage.o $(OUTDIR)/gnoga-gui-base.o \
	$(OUTDIR)/gnoga-gui-document.o \
	$(OUTDIR)/gnoga-gui-element-canvas-context_2d-plotting.o \
	$(OUTDIR)/gnoga-gui-element-canvas-context_2d.o \
	$(OUTDIR)/gnoga-gui-element-canvas.o \
	$(OUTDIR)/gnoga-gui-element-common.o \
	$(OUTDIR)/gnoga-gui-element-form-fieldset.o \
	$(OUTDIR)/gnoga-gui-element-form.o \
	$(OUTDIR)/gnoga-gui-element-iframe.o \
	$(OUTDIR)/gnoga-gui-element-list.o \
	$(OUTDIR)/gnoga-gui-element-multimedia.o \
	$(OUTDIR)/gnoga-gui-element-phrase.o \
	$(OUTDIR)/gnoga-gui-element-section.o \
	$(OUTDIR)/gnoga-gui-element-style_block.o \
	$(OUTDIR)/gnoga-gui-element-svg.o \
	$(OUTDIR)/gnoga-gui-element-table.o $(OUTDIR)/gnoga-gui-element.o \
	$(OUTDIR)/gnoga-gui-location.o $(OUTDIR)/gnoga-gui-navigator.o \
	$(OUTDIR)/gnoga-gui-plugin-ace_editor.o \
	$(OUTDIR)/gnoga-gui-plugin-boot_strap.o \
	$(OUTDIR)/gnoga-gui-plugin-jquery.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui-widget.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui.o \
	$(OUTDIR)/gnoga-gui-plugin-macgap.o \
	$(OUTDIR)/gnoga-gui-plugin-message_boxes.o \
	$(OUTDIR)/gnoga-gui-screen.o $(OUTDIR)/gnoga-gui-view-card.o \
	$(OUTDIR)/gnoga-gui-view-console.o $(OUTDIR)/gnoga-gui-view-docker.o \
	$(OUTDIR)/gnoga-gui-view-grid.o $(OUTDIR)/gnoga-gui-view.o \
	$(OUTDIR)/gnoga-gui-window.o $(OUTDIR)/gnoga-server-connection.o \
	$(OUTDIR)/gnoga-server-database-mysql.o \
	$(OUTDIR)/gnoga-server-database-sqlite.o \
	$(OUTDIR)/gnoga-server-database.o $(OUTDIR)/gnoga-server-migration.o \
	$(OUTDIR)/gnoga-server-mime.o $(OUTDIR)/gnoga-server-model-queries.o \
	$(OUTDIR)/gnoga-server-model-table.o $(OUTDIR)/gnoga-server-model.o \
	$(OUTDIR)/gnoga-server-template_parser-python.o \
	$(OUTDIR)/gnoga-server-template_parser-simple.o \
	$(OUTDIR)/gnoga-server-template_parser.o $(OUTDIR)/gnoga-server.o \
	$(OUTDIR)/gnoga-types-colors.o $(OUTDIR)/gnoga-types.o \
	$(OUTDIR)/gnoga.o $(OUTDIR)/gnoga_doc-main.o \
	$(OUTDIR)/gnoga_doc-token.o $(OUTDIR)/gnoga_doc.o \
	$(OUTDIR)/gnoga_make-main.o $(OUTDIR)/gnoga_make.o
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/gnoga-gui-plugin-ace_editor.o \
	$(OUTDIR)/adablog-controller.o $(OUTDIR)/adablog-main.o \
	$(OUTDIR)/adablog-migrations.o $(OUTDIR)/adablog-view.o \
	$(OUTDIR)/adaedit.o $(OUTDIR)/othello_game.o \
	$(OUTDIR)/othello_pkg-callbacks.o $(OUTDIR)/othello_pkg.o \
	$(OUTDIR)/gnoga-gui-plugin-boot_strap.o $(OUTDIR)/chattanooga-db.o \
	$(OUTDIR)/chattanooga-program.o $(OUTDIR)/chattanooga-ui.o \
	$(OUTDIR)/connect_four.o $(OUTDIR)/connectfour.o \
	$(OUTDIR)/db_maker.o $(OUTDIR)/movies.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui-widget.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui.o $(OUTDIR)/about_dialog_pkg.o \
	$(OUTDIR)/block_engine.o $(OUTDIR)/game_engine.o \
	$(OUTDIR)/gnoga_extras.o $(OUTDIR)/linxtris.o \
	$(OUTDIR)/main_window_pkg-callbacks.o $(OUTDIR)/main_window_pkg.o \
	$(OUTDIR)/new_score_dialog_pkg.o $(OUTDIR)/preferences_window_pkg.o \
	$(OUTDIR)/scores_window_pkg.o \
	$(OUTDIR)/gnoga-gui-plugin-message_boxes.o \
	$(OUTDIR)/field-operations.o $(OUTDIR)/mine_detector.o \
	$(OUTDIR)/user_if.o $(OUTDIR)/password_gen-program.o \
	$(OUTDIR)/password_gen-ui.o $(OUTDIR)/random_int-program.o \
	$(OUTDIR)/random_int-ui.o $(OUTDIR)/snake-connection.o \
	$(OUTDIR)/snake-main.o $(OUTDIR)/tic_tac_toe-program.o \
	$(OUTDIR)/tic_tac_toe-ui-logic.o $(OUTDIR)/tic_tac_toe-ui.o \
	$(OUTDIR)/tutorial_01.o $(OUTDIR)/tutorial_02.o \
	$(OUTDIR)/tutorial_03.o $(OUTDIR)/tutorial_04.o \
	$(OUTDIR)/tutorial_05.o $(OUTDIR)/tutorial_06.o \
	$(OUTDIR)/tutorial_07.o $(OUTDIR)/tutorial_08.o \
	$(OUTDIR)/tutorial_09.o $(OUTDIR)/tutorial_widget.o \
	$(OUTDIR)/tutorial_10.o $(OUTDIR)/tutorial_11.o \
	$(OUTDIR)/tutorial_01.o $(OUTDIR)/gnoga-application-gtk_window.o \
	$(OUTDIR)/gnoga-application-multi_connect.o \
	$(OUTDIR)/gnoga-application-singleton.o \
	$(OUTDIR)/gnoga-application.o $(OUTDIR)/gnoga-client-bind_page.o \
	$(OUTDIR)/gnoga-client-storage.o $(OUTDIR)/gnoga-gui-base.o \
	$(OUTDIR)/gnoga-gui-document.o \
	$(OUTDIR)/gnoga-gui-element-canvas-context_2d-plotting.o \
	$(OUTDIR)/gnoga-gui-element-canvas-context_2d.o \
	$(OUTDIR)/gnoga-gui-element-canvas.o \
	$(OUTDIR)/gnoga-gui-element-common.o \
	$(OUTDIR)/gnoga-gui-element-form-fieldset.o \
	$(OUTDIR)/gnoga-gui-element-form.o \
	$(OUTDIR)/gnoga-gui-element-iframe.o \
	$(OUTDIR)/gnoga-gui-element-list.o \
	$(OUTDIR)/gnoga-gui-element-multimedia.o \
	$(OUTDIR)/gnoga-gui-element-phrase.o \
	$(OUTDIR)/gnoga-gui-element-section.o \
	$(OUTDIR)/gnoga-gui-element-style_block.o \
	$(OUTDIR)/gnoga-gui-element-svg.o \
	$(OUTDIR)/gnoga-gui-element-table.o $(OUTDIR)/gnoga-gui-element.o \
	$(OUTDIR)/gnoga-gui-location.o $(OUTDIR)/gnoga-gui-navigator.o \
	$(OUTDIR)/gnoga-gui-plugin-ace_editor.o \
	$(OUTDIR)/gnoga-gui-plugin-boot_strap.o \
	$(OUTDIR)/gnoga-gui-plugin-jquery.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui-widget.o \
	$(OUTDIR)/gnoga-gui-plugin-jqueryui.o \
	$(OUTDIR)/gnoga-gui-plugin-macgap.o \
	$(OUTDIR)/gnoga-gui-plugin-message_boxes.o \
	$(OUTDIR)/gnoga-gui-screen.o $(OUTDIR)/gnoga-gui-view-card.o \
	$(OUTDIR)/gnoga-gui-view-console.o $(OUTDIR)/gnoga-gui-view-docker.o \
	$(OUTDIR)/gnoga-gui-view-grid.o $(OUTDIR)/gnoga-gui-view.o \
	$(OUTDIR)/gnoga-gui-window.o $(OUTDIR)/gnoga-server-connection.o \
	$(OUTDIR)/gnoga-server-database-mysql.o \
	$(OUTDIR)/gnoga-server-database-sqlite.o \
	$(OUTDIR)/gnoga-server-database.o $(OUTDIR)/gnoga-server-migration.o \
	$(OUTDIR)/gnoga-server-mime.o $(OUTDIR)/gnoga-server-model-queries.o \
	$(OUTDIR)/gnoga-server-model-table.o $(OUTDIR)/gnoga-server-model.o \
	$(OUTDIR)/gnoga-server-template_parser-python.o \
	$(OUTDIR)/gnoga-server-template_parser-simple.o \
	$(OUTDIR)/gnoga-server-template_parser.o $(OUTDIR)/gnoga-server.o \
	$(OUTDIR)/gnoga-types-colors.o $(OUTDIR)/gnoga-types.o \
	$(OUTDIR)/gnoga.o $(OUTDIR)/gnoga_doc-main.o \
	$(OUTDIR)/gnoga_doc-token.o $(OUTDIR)/gnoga_doc.o \
	$(OUTDIR)/gnoga_make-main.o $(OUTDIR)/gnoga_make.o

COMPILE=gnat -O -c $(CFG_INC) -o "$(OUTDIR)/$(*F).o" "$<"
LINK=gnat -O -o "$(OUTFILE)" $(OBJ) $(CFG_LIB)
COMPILE_ADA=gnat -O -c -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_ADB=gnat -O -c -o "$(OUTDIR)/$(*F).o" "$<"

# Pattern rules
$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/ace_editor/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/chattanooga/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adablog/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adaedit/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/mine_detector/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-08/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-01/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/linxtris/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/snake/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial_01/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/jqueryui/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/message_boxes/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-09/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/bootstrap/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-04/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/db_maker/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/password_gen/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-06/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-05/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tools/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-11/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-07/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adaothello/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-10/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/connect_four/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-02/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/tic_tac_toe/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-03/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/random_int/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/ace_editor/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/chattanooga/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adablog/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adaedit/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/mine_detector/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-08/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-01/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/linxtris/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/snake/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial_01/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/jqueryui/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/message_boxes/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-09/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/components/bootstrap/src/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-04/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/db_maker/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/password_gen/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-06/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-05/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tools/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-11/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-07/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/adaothello/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-10/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/connect_four/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-02/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/tic_tac_toe/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/tutorial/tutorial-03/%.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : ../../vendor/github.com/gnoga/demo/random_int/%.adb
	$(COMPILE_ADB)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR) $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall
	@$(MAKE) -f "$(strip $(MAKEFILE_LIST))" $(MAKEFLAGS) all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# include dependencies:
#
