name = "ada_lib_gnoga"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

project-files = "ada_lib_gnoga.gpr"

#[[depends-on]]
#ada_lib = "*"
#
#[[pins]]
#ada_lib = { path='..' }

[[depends-on]]
gnoga = "~0.1.0-dev"

[[pins]]
gnoga = { path='../../vendor/github.com/gnoga' }

[[depends-on]]
aunit = "~0.1.0-dev"

[[pins]]
aunit = { path='../../aunit' }

[[depends-on]]
ada_lib_base = "~0.1.0-dev"

[[pins]]
ada_lib_base = { path="../ada_lib_base" }

[[depends-on]]
ada_lib_options = "~0.1.0-dev"

[[pins]]
ada_lib_options = { path="../ada_lib_options" }

[[depends-on]]
ada_lib_test_lib = "~0.1.0-dev"

[[pins]]
ada_lib_test_lib = { path="../ada_lib_base" }




