name = "ada_lib_base"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""

project-files = "ada_lib_base.gpr"

[[depends-on]]
alr_environment = "*"

[[pins]]
alr_environment = { path='../..' }

[[depends-on]]
ada_lib_options = "~0.1.0-dev"

[[pins]]
ada_lib_options = { path="../ada_lib_options" }

[[depends-on]]
gnatcoll_minimal = "*"





